Projeto04/Models/Licenca.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Projeto02.Models
{
    public class Licenca : EntityBase
    {
        [Required(ErrorMessage ="A chave do software é obrigatória")] //Chave do Software
        public string Chave { get; set; }
        [Required(ErrorMessage ="Quantidade obrigatória")]
        [RegularExpression(@"0*[1-9][0-9]*", ErrorMessage ="A quantidade deve ser maior que ZERO")]//Quantidade de Software
        public int Quantidade { get; set; }
         //Software
        public virtual Software Software { get; set; }
        //[Required(ErrorMessage = "Software requerido")]
        public int SoftwareId { get; set; }
    }
}

Projeto04/Models/SolicitacaoLicenca.cs
using Projeto02.Models.Enum;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Projeto02.Models
{
    public class SolicitacaoLicenca : EntityBase
    {
        [Required] //Referencia de Software
        public virtual Software Software { get; set; }
        [Required] //Id de Software
        public int SoftwareId { get; set; }
        [Required] //Data de inicial para usar a licenca
        public DateTime DataInicio { get; set; }
        [Required] //Data Final para usar a licenca
        public DateTime DataTermino { get; set; }
        [Required] //Fazer Numero
        public int Protocolo { get; set; }

        public string Justificacao { get; set; }

        [Required] //Usuario
        public virtual Usuario Usuario { get; set; }
        [Required] // Id do Usuario
        public int UsuarioId { get; set; }
        //Motivo de uso
        public string MotivoDeUso { get; set; }
        [Required]
        public Status Status { get; set; }
    }
}

Projeto04/Controllers/LicencaController.cs
using Projeto02.DAO;
using Projeto02.Filtro;
using Projeto02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto02.Controllers
{
    [AutorizacaoFilter]
    public class LicencaController : Controller
    {
        // GET: Licenca
        private IList<Software> listaSoftwares
        {
            get
            {
                var dao = new SoftwareDAO();
                return dao.Lista();
            }
        }
        public ActionResult Index()
        {
            var dao = new LicencaDAO();
            IList<Licenca> licenca = dao.Lista();
            ViewBag.Licenca = licenca;
            return View();
        }
        [HttpPost]        
        public ActionResult Adiciona(Licenca licenca)
        {
            if (ModelState.IsValid)
            {
                var dao = new LicencaDAO();
                dao.Adiciona(licenca);
                return View("Adiciona");
            }
            ViewBag.Software = listaSoftwares;

            return View("Form",licenca);
        }

        public ActionResult Form()
        {
            ViewBag.Software = listaSoftwares;            
            return View(new Licenca());
        }
        public ActionResult Remover(int id)
        {
            var dao = new LicencaDAO();
            Licenca licenca = dao.BuscaPorIdWhere(id);
            dao.Remover(licenca);
            return RedirectToAction("Index");
        }

        public ActionResult Alterar(int id)
        {
            var dao = new LicencaDAO();
            Licenca licenca = dao.BuscaPorId(id);
            ViewBag.Licenca = licenca;
            return View(licenca);
        }

        [HttpGet]
        public ActionResult Atualiza(int id)
        {
            var dao = new LicencaDAO();
            Licenca licenca = dao.BuscaPorId(id);
            return View(licenca);
        }

        [HttpPost]
        public ActionResult Atualiza([Bind(Include = "Id, Chave, Quantidade, SoftwareId, UsuarioId")] Licenca licenca)
        {
            var dao = new LicencaDAO();
            dao.Atualiza(licenca);
            return View();
        }
        public ActionResult DecrementaQtd(int id)
        {
            LicencaDAO dao = new LicencaDAO();
            Licenca licenca = dao.BuscaPorId(id);
            licenca.Quantidade--;
            dao.Atualiza(licenca);
            return Json(licenca);
        }
    }
}

Projeto04/Controllers/SolicitacaoLicencaController.cs
using Projeto02.DAO;
using Projeto02.ExtensionMethods;
using Projeto02.Filtro;
using Projeto02.Models;
using Projeto02.Models.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto02.Controllers
{
    [AutorizacaoFilter]
    public class SolicitacaoLicencaController : Controller
    {
        // GET: SolicitacaoLicenca
        public ActionResult Index()
        {
            var dao = new SolicitacaoLicencaDAO();
            IList<SolicitacaoLicenca> solicitacaoLicenca = dao.Lista();
            ViewBag.SolicitacaoLicenca = solicitacaoLicenca;
            return View();
        }

        public ActionResult Adiciona(SolicitacaoLicenca solicitacaoLicenca)
        {
            //Tratar pra não selecionar usuário. Pegar da SESSION, porque FUNCIONA
            var usuario = (Usuario)Session["usuarioLogin"];

            var dao = new SolicitacaoLicencaDAO();
            var ultimoProtocolo = dao.SelecionarNumeroMaiorProtocolo();
            
            solicitacaoLicenca.Protocolo = ultimoProtocolo + 1;
            solicitacaoLicenca.UsuarioId = usuario.Id;
            dao.Adiciona(solicitacaoLicenca);

            return View();
        }

        public ActionResult Form()
        {
            var dao = new SoftwareDAO();
            IList<Software> softwares = dao.Lista();
            ViewBag.Software = softwares;

            var daoo = new UsuarioDAO();
            IList<Usuario> usuario = daoo.Lista();
            ViewBag.Usuario = usuario;

            ViewBag.SolicitacaoLicenca = new SolicitacaoLicenca();

            ViewBag.ListaEnum = Status.AguardandoAprovacaodoGestor.ToSelectList();

            return View();
        }
        public ActionResult Remover(int id)
        {
            var dao = new SolicitacaoLicencaDAO();
            SolicitacaoLicenca solicitacaoLicenca = dao.BuscaPorIdWhere(id);
            dao.Remover(solicitacaoLicenca);
            return RedirectToAction("Index");
        }
        public ActionResult Alterar(int id)
        {
            var dao = new SoftwareDAO();
            IList<Software> softwares = dao.Lista();
            ViewBag.Software = softwares;

            var daoo = new SolicitacaoLicencaDAO();
            SolicitacaoLicenca solicitacaoLicenca = daoo.BuscaPorId(id);
            ViewBag.SolicitacaoLicenca = solicitacaoLicenca;

            ViewBag.ListaEnum = Status.AguardandoAprovacaodoGestor.ToSelectList();

            return View(solicitacaoLicenca);
        }

        [HttpGet]
        public ActionResult Atualiza(int id)
        {
            var dao = new SolicitacaoLicencaDAO();
            SolicitacaoLicenca solicitacaoLicenca = dao.BuscaPorId(id);
            return View(solicitacaoLicenca);
        }

        [HttpPost]
        public ActionResult Atualiza(int id, Status status, [Bind(Include = "Id, SoftwareId, DataInicio, DataTermino, UsuarioId, MotivoDeUso, Status, Justificacao")] SolicitacaoLicenca solicitacaoLicenca)
        {
            // Corrigir pois está liberando o Menu de ADM
            solicitacaoLicenca.Id = id;
            solicitacaoLicenca.Status = status;
            var dao = new SolicitacaoLicencaDAO();
            dao.AlterarSituacao(solicitacaoLicenca);
            return View();
        }

        public ActionResult Licenca()
        {
            var dao = new SolicitacaoLicencaDAO();
            IList<SolicitacaoLicenca> solicitacaoLicenca = dao.Lista();
            ViewBag.SolicitacaoLicenca = solicitacaoLicenca;
            return View();
        }

        public ActionResult Justificacao(int id)
        {
            var dao = new SolicitacaoLicencaDAO();
            IList<SolicitacaoLicenca> solicitacaoLicenca = dao.Lista();
            ViewBag.SolicitacaoLicenca = solicitacaoLicenca.Where(r => r.Id == id);
            return View();
        }

        public ActionResult GestorLicenca()
        {
            var dao = new SolicitacaoLicencaDAO();
            IList<SolicitacaoLicenca> solicitacaoLicenca = dao.Lista();
            ViewBag.SolicitacaoLicenca = solicitacaoLicenca.Where(r => r.Status == Status.AguardandoAprovacaodoGestor);
            return View();
        }

        public ActionResult GesrtorAlterar(int id)
        {
            var dao = new SoftwareDAO();
            IList<Software> softwares = dao.Lista();
            ViewBag.Software = softwares;

            var daoo = new SolicitacaoLicencaDAO();
            SolicitacaoLicenca solicitacaoLicenca = daoo.BuscaPorId(id);
            ViewBag.SolicitacaoLicenca = solicitacaoLicenca;

            ViewBag.ListaEnum = Status.AguardandoAprovacaodoGestor.ToSelectList();

            return View(solicitacaoLicenca);
        }
    }
}

Projeto04/Views/SolicitacaoLicenca/Adiciona.cshtml
<div>
    <h1>Pedido Feito com sucesso!</h1>

    <a class="nav-link" href="/SolicitacaoLicenca/Licenca">
        <p class="btn btn-primary">Voltar para a lista</p>
    </a>

</div>

Projeto04/Views/SolicitacaoLicenca/Alterar.cshtml
@{
    Layout = "~/Views/Shared/_AdmLayout.cshtml";
}

<form action="/SolicitacaoLicenca/Atualiza/@ViewBag.SolicitacaoLicenca.Id" method="post">

    <label for="SoftwareId">Software Id: </label>
    <select id="SoftwareId" name="solicitacaoLicenca.SoftwareId" class="form-control">
        @foreach (var software in ViewBag.Software)
        {
            <option value="@software.Id" selected="@software.Id.Equals(ViewBag.SolicitacaoLicenca.SoftwareId)">
                @software.NomeSoftware
            </option>
        }
    </select>

    <label for="DataInicio">Data Inicio: </label>
    <input type="date" id="DataInicio" value="@ViewBag.SolicitacaoLicenca.DataInicio" name="solicitacaoLicenca.DataInicio" class="form-control" />

    <label for="DataTermino">Data Termino: </label>
    <input type="date" id="DataTermino" value="@ViewBag.SolicitacaoLicenca.DataTermino" name="solicitacaoLicenca.DataTermino" class="form-control" />

    <label for="MotivoDeUso">Motivo De Uso: </label>
    <input id="MotivoDeUso" value="@ViewBag.SolicitacaoLicenca.MotivoDeUso" name="solicitacaoLicenca.MotivoDeUso" class="form-control" />

    <label for="Status">Status:</label>
    <select id="Status" name="Status" class="form-control">
        @foreach (var status in ViewBag.ListaEnum)
        {
            <option value="@status.Value"
                    selected="@Convert.ToInt32(status.Value).Equals(Convert.ToInt32(ViewBag.SolicitacaoLicenca.Status))">
                @status.Text
            </option>
        }
    </select>

    @*<label for="UsuarioId">Usuario: </label>
    <input id="UsuarioId" value="@ViewBag.SolicitacaoLicenca.UsuarioId" name="solicitacaoLicenca.UsuarioId" class="form-control" />*@

    <input class="btn btn-primary" type="submit" value="Alterar" />

</form>

Projeto04/Views/SolicitacaoLicenca/Atualiza.cshtml
@{
    Layout = "~/Views/Shared/_GestorLayout.cshtml";
}

<div>
    <h1>Pedido Atualizado com sucesso</h1>

    <a class="nav-link" href="/Home/Gestor">
        <p class="btn btn-primary">Voltar para a lista</p>
    </a>
</div>

Projeto04/Views/SolicitacaoLicenca/Form.cshtml
@model Projeto02.Models.SolicitacaoLicenca

<h3 class="form- active">Cadastrar Pedidos</h3>
<div>
    <form action="/SolicitacaoLicenca/Adiciona" method="post">

        <label for="nome">Nome:</label>
        <select id="nome" name="SolicitacaoLicenca.SoftwareId" class="form-control">
            @foreach (var software in ViewBag.Software)
            {
                <option value="@software.Id" selected="@software.Id.Equals(ViewBag.SoftwareId)">
                    @software.NomeSoftware
                </option>

            }
        </select>

        <label for="datainicio">Data Inicio:</label>
        <input type="date" name="SolicitacaoLicenca.DataInicio" id="datainicio" class="form-control" />

        <label for="datatermino">Data Termino:</label>
        <input type="date" name="SolicitacaoLicenca.DataTermino" id="datatermino" class="form-control" />

        @*<label for="status">Status:</label>
            <select id="status" name="SolicitacaoLicenca.Status" class="form-control">
                <option selected="selected" value="">Selecione o Status</option>
                @foreach (var status in ViewBag.ListaEnum)
                {
                    <option value="@status.Value">
                        @status.Text
                    </option>
                }
            </select>*@

        <label for="motivoDeUso">Motivo De Uso:</label>
        <input type="text" name="SolicitacaoLicenca.MotivoDeUso" id="motivoDeUso" class="form-control" />
        <br />
        @*<label for="usuarioId">UsuarioId:</label>
        <input type="text" name="SolicitacaoLicenca.UsuarioId" id="usuarioId" class="form-control" />*@

        <input class="btn btn-primary" type="submit" value="Completar" />

    </form>
</div>

Projeto04/Views/SolicitacaoLicenca/GesrtorAlterar.cshtml
@{
    Layout = "~/Views/Shared/_GestorLayout.cshtml";
}

<form action="/SolicitacaoLicenca/Atualiza/@ViewBag.SolicitacaoLicenca.Id" method="post">

    <label for="Status">Status: </label>
    <select id="Status" name="Status" class="form-control">
        @foreach (var status in ViewBag.ListaEnum)
        {
            <option value="@status.Value"
                    selected="@Convert.ToInt32(status.Value).Equals(Convert.ToInt32(ViewBag.SolicitacaoLicenca.Status))">
                @status.Text
            </option>
        }
    </select>

    <label for="justificacao">Justificacao:</label>
    <input type="text" value="@ViewBag.SolicitacaoLicenca.Justificacao" name="Justificacao" class="form-control" />
    <br />

    <input class="btn btn-primary" type="submit" value="Alterar" />

</form>

Projeto04/Views/SolicitacaoLicenca/GestorLicenca.cshtml
@{
    Layout = "~/Views/Shared/_GestorLayout.cshtml";
}
<td>
    <a class="btn btn-primary pull-right" href="Form/">Adicionar</a>
</td>
<h2>Lista de Pedidos do sistema.</h2>
<table class="table table-hover">
    <thead>
        <tr>
            @*<th>Id</th>*@
            <th>Nome da Licenca</th>
            <th>Data Inicio</th>
            <th>Data Termino</th>
            <th>Protocolo</th>
            <th>Motivo de Uso</th>
            <th>Status</th>
            <th>Usuario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var solicitacaoLicenca in ViewBag.SolicitacaoLicenca)
        {
            <tr>
                @*<td>@solicitacaoLicenca.Id</td>*@
                <td>@solicitacaoLicenca.Software.NomeSoftware</td>
                <td>@solicitacaoLicenca.DataInicio.ToString("dd/MM/yyyy")</td>
                @if (solicitacaoLicenca.DataTermino == DateTime.MinValue)
                {
                    <td></td>
                }
                else
                {
                    <td>@solicitacaoLicenca.DataTermino.ToString("dd/MM/yyyy")</td>
                }
                <td>@solicitacaoLicenca.Protocolo</td>
                <td>@solicitacaoLicenca.MotivoDeUso</td>
                <td>@solicitacaoLicenca.Status</td>
                <td>@solicitacaoLicenca.Usuario.Login</td>

                <td>
                    <a class="btn btn-primary" href="GesrtorAlterar/@solicitacaoLicenca.Id">Atualizar</a>
                </td>
                @*<td>
                    <a class="btn btn-primary" href="~/SolicitacaoLicenca/GestorLicenca" onclick="aumenta(@solicitacaoLicenca.Id)">Sim</a>
                </td>
                <td>
                    <a class="btn btn-primary" href="~/SolicitacaoLicenca/GestorLicenca" onclick="decrementa(@solicitacaoLicenca.Id)">Não</a>
                </td>*@
            </tr>
        }
    </tbody>
</table>

@*<script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
<script type="text/javascript">

    function decrementa(solicitacaoLicencaId) {
        var url = "@Url.Action("DecrementaQtd","SolicitacaoLicenca")";
        var params = { id: solicitacaoLicencaId };
        $.post(url, params, atualiza);

        function atualiza(resposta) {
            var elemento = $("#status" + resposta.id);
           elemento.html(resposta.Status);
        }
    }

    function aumenta(solicitacaoLicencaId) {
        var urll = "@Url.Action("AumentaQtd","SolicitacaoLicenca")";
        var paramsa = { id: solicitacaoLicencaId };
        $.post(urll, paramsa, atualizar);

        function atualizar(resposta) {
            var elemento = $("#status" + resposta.id);
           elemento.html(resposta.Status);
        }
    }
</script>*@

Projeto04/Views/SolicitacaoLicenca/Index.cshtml
@{
    Layout = "~/Views/Shared/_AdmLayout.cshtml";
}

<h2>Lista de Pedidos do sistema.</h2>
<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome da Licenca</th>
            <th>Data Inicio</th>
            <th>Data Termino</th>
            <th>Protocolo</th>
            <th>Motivo de Uso</th>
            <th>Status</th>
            <th>Usuario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var solicitacaoLicenca in ViewBag.SolicitacaoLicenca)
        {
            <tr>
                <td>@solicitacaoLicenca.Id</td>
                <td>@solicitacaoLicenca.Software.NomeSoftware</td>
                <td>@solicitacaoLicenca.DataInicio.ToString("dd/MM/yyyy")</td>
                @if (solicitacaoLicenca.DataTermino == DateTime.MinValue)
                {
                    <td></td>
                }
                else
                {
                    <td>@solicitacaoLicenca.DataTermino.ToString("dd/MM/yyyy")</td>
                }
                <td>@solicitacaoLicenca.Protocolo</td>
                <td>@solicitacaoLicenca.MotivoDeUso</td>
                <td>@solicitacaoLicenca.Status</td>
                <td>@solicitacaoLicenca.Usuario.Login</td>
                <td>
                    <a class="btn btn-primary" href="Alterar/@solicitacaoLicenca.Id">Atualizar</a>
                </td>
                <td>
                    <a class="btn btn-primary" href="Remover/@solicitacaoLicenca.Id">Remover</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Projeto04/Views/SolicitacaoLicenca/Justificacao.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Projeto02.Models.SolicitacaoLicenca

<h2>Justificação.</h2>
<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th>Nome da Licenca</th>
            <th>Usuario</th>
            <th>Justificação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var solicitacaoLicenca in ViewBag.SolicitacaoLicenca)
        {
            <tr>
                <td>@solicitacaoLicenca.Software.NomeSoftware</td>
                <td>@solicitacaoLicenca.Usuario.Login</td>
                <td>@solicitacaoLicenca.Justificacao</td>
            </tr>
        }
    </tbody>
</table>

Projeto04/Views/SolicitacaoLicenca/Licenca.cshtml
<td>
    <a class="btn btn-primary pull-right" href="Form/">Pedido</a>
</td>
<h2>Lista de Pedidos do sistema.</h2>

<table class="table table-hover">
    <thead>
        <tr>
            @*<th>Id</th>*@
            <th>Nome da Licenca</th>
            <th>Data Inicio</th>
            <th>Data Termino</th>
            <th>Protocolo</th>
            <th>Motivo de Uso</th>
            <th>Status</th>
            <th>Usuario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var solicitacaoLicenca in ViewBag.SolicitacaoLicenca)
        {
            <tr>
                @*<td>@solicitacaoLicenca.Id</td>*@
                <td>@solicitacaoLicenca.Software.NomeSoftware</td>
                <td>@solicitacaoLicenca.DataInicio.ToString("dd/MM/yyyy")</td>
                @if (solicitacaoLicenca.DataTermino == DateTime.MinValue)
                {
                    <td></td>
                }
                else
                {
                    <td>@solicitacaoLicenca.DataTermino.ToString("dd/MM/yyyy")</td>
                }
                <td>@solicitacaoLicenca.Protocolo</td>
                <td>@solicitacaoLicenca.MotivoDeUso</td>
                <td>@solicitacaoLicenca.Status</td>
                <td>@solicitacaoLicenca.Usuario.Login</td>
                <td>
                    <a class="btn btn-primary" href="Justificacao/@solicitacaoLicenca.Id">Justificativa</a>
                </td>
            </tr>
        }
    </tbody>
</table>