Projeto04/Models/Gestor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Projeto02.Models
{
    public class Gestor : Funcionario
    {
        public bool EhGestor;
    }
}

Projeto04/Controllers/CargoController.cs
using Projeto02.DAO;
using Projeto02.Filtro;
using Projeto02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto02.Controllers
{
    [AutorizacaoFilter]
    public class CargoController : Controller
    {
        // GET: Cargo
        public ActionResult Index()
        {
            CargoDAO dao = new CargoDAO();
            IList<Cargo> cargo = dao.Lista();
            ViewBag.Cargo = cargo;
            return View();
        }
        [HttpPost]
        
        public ActionResult Adiciona(Cargo cargo)
        {
            if (ModelState.IsValid)
            {
                CargoDAO dao = new CargoDAO();
                dao.Adiciona(cargo);
                return View("Adiciona");
            }
            return View("Form");
        }
        [Route("adm/CadastrarCargo")]
        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Remover(int id)
        {
            var dao = new CargoDAO();
            Cargo cargo = dao.BuscaPorIdWhere(id);
            dao.Remover(cargo);
            return RedirectToAction("Index");
        }

        public ActionResult Alterar(int id)
        {
            var dao = new CargoDAO();
            Cargo cargo = dao.BuscaPorId(id);
            ViewBag.Cargo = cargo;

            return View(cargo);
        }

        [HttpGet]
        public ActionResult Atualiza(int id)
        {
            var dao = new CargoDAO();
            Cargo cargo = dao.BuscaPorId(id);
            return View(cargo);
        }

        [HttpPost]
        public ActionResult Atualiza([Bind(Include = "Id, NomeCargo")] Cargo cargo)
        {
            var dao = new CargoDAO();
            dao.Atualiza(cargo);
            return View();
        }
    }
}

Projeto04/Controllers/EquipeController.cs
using Projeto02.DAO;
using Projeto02.Filtro;
using Projeto02.Models;
using Projeto02.Models.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto02.Controllers
{
    [AutorizacaoFilter]
    public class EquipeController : Controller
    {
        // GET: Equipe
        public ActionResult Index()
        {
            EquipeDAO dao = new EquipeDAO();
            IList<Equipe> equipe = dao.Lista();
            ViewBag.Equipe = equipe;
            return View();
        }
        [HttpPost]
        public ActionResult Adiciona(Equipe equipe)
        {
            if (ModelState.IsValid)
            {
                EquipeDAO dao = new EquipeDAO();
                dao.Adiciona(equipe);
                return View("Adiciona");
            }
            return View("Form");
        }

        public ActionResult Form()
        {
            var dao = new FuncionarioDAO();
            IList<Funcionario> funcionario = dao.Lista().Where(x => x.TipoPerfil == TipoPerfil.Gestor).ToList();
            ViewBag.Funcionario = funcionario;

            return View();
        }
        public ActionResult Remover(int id)
        {
            var dao = new EquipeDAO();
            Equipe equipe = dao.BuscaPorIdWhere(id);
            dao.Remover(equipe);
            return RedirectToAction("Index");
        }

        public ActionResult Alterar(int id)
        {
            var dao = new EquipeDAO();
            Equipe equipe = dao.BuscaPorId(id);
            ViewBag.Equipe = equipe;

            return View(equipe);
        }

        [HttpGet]
        public ActionResult Atualiza(int id)
        {
            var dao = new EquipeDAO();
            Equipe equipe = dao.BuscaPorId(id);
            return View(equipe);
        }

        [HttpPost]
        public ActionResult Atualiza([Bind(Include = "Id, NomeEquipe, GestorId")] Equipe equipe)
        {
            var dao = new EquipeDAO();
            dao.Atualiza(equipe);
            return View();
        }
    }
}

Projeto04/Controllers/HomeController.cs
using Projeto02.Filtro;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Projeto02.Controllers
{
    [AutorizacaoFilter]

    public class HomeController : Controller
    {
        //[AutorizacaoFilter]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        //[AutorizacaoFilter]
        public ActionResult Adm()
        {

            return View();
        }

        public ActionResult Gestor()
        {
            return View();
        }
    }
}

Projeto04/Controllers/LicencaController.cs
using Projeto02.DAO;
using Projeto02.Filtro;
using Projeto02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto02.Controllers
{
    [AutorizacaoFilter]
    public class LicencaController : Controller
    {
        // GET: Licenca
        private IList<Software> listaSoftwares
        {
            get
            {
                var dao = new SoftwareDAO();
                return dao.Lista();
            }
        }
        public ActionResult Index()
        {
            var dao = new LicencaDAO();
            IList<Licenca> licenca = dao.Lista();
            ViewBag.Licenca = licenca;
            return View();
        }
        [HttpPost]        
        public ActionResult Adiciona(Licenca licenca)
        {
            if (ModelState.IsValid)
            {
                var dao = new LicencaDAO();
                dao.Adiciona(licenca);
                return View("Adiciona");
            }
            ViewBag.Software = listaSoftwares;

            return View("Form",licenca);
        }

        public ActionResult Form()
        {
            ViewBag.Software = listaSoftwares;            
            return View(new Licenca());
        }
        public ActionResult Remover(int id)
        {
            var dao = new LicencaDAO();
            Licenca licenca = dao.BuscaPorIdWhere(id);
            dao.Remover(licenca);
            return RedirectToAction("Index");
        }

        public ActionResult Alterar(int id)
        {
            var dao = new LicencaDAO();
            Licenca licenca = dao.BuscaPorId(id);
            ViewBag.Licenca = licenca;
            return View(licenca);
        }

        [HttpGet]
        public ActionResult Atualiza(int id)
        {
            var dao = new LicencaDAO();
            Licenca licenca = dao.BuscaPorId(id);
            return View(licenca);
        }

        [HttpPost]
        public ActionResult Atualiza([Bind(Include = "Id, Chave, Quantidade, SoftwareId, UsuarioId")] Licenca licenca)
        {
            var dao = new LicencaDAO();
            dao.Atualiza(licenca);
            return View();
        }
        public ActionResult DecrementaQtd(int id)
        {
            LicencaDAO dao = new LicencaDAO();
            Licenca licenca = dao.BuscaPorId(id);
            licenca.Quantidade--;
            dao.Atualiza(licenca);
            return Json(licenca);
        }
    }
}

Projeto04/Controllers/UsuarioController.cs
using Projeto02.DAO;
using Projeto02.Models;
using Projeto02.Models.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Projeto02.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Autentica(String login, String senha)
        {
            UsuarioDAO dao = new UsuarioDAO();
            Usuario usuario = dao.Busca(login, senha);
            if (usuario != null)
            {
                Session["usuarioLogado"] = usuario;
                Session["nomeUsuario"] = usuario.Funcionario.Nome;
                Session["TipoPerfil"] = usuario.Funcionario.TipoPerfil;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("index");
            }

        }

        [HttpPost]
        public ActionResult Adiciona(Usuario usuario)
        {
            FuncionarioDAO funDao = new FuncionarioDAO();
            var idFunc = funDao.BuscarPorCodigoVerificacao(usuario.CodigoVerificacao);

            if (idFunc == 0)
            {
                ModelState.AddModelError("codigoVerificacao", "Código de verificação informado inválido.");
                return View("Form");
            }

            usuario.FuncionarioId = idFunc;

            UsuarioDAO dao = new UsuarioDAO();
            dao.Adiciona(usuario);
            return View("Adiciona");
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Visualiza()
        {
            var usuario1 = new Usuario();
            var dao = new UsuarioDAO();
            IList<Usuario> usuario = dao.Lista();
            ViewBag.Usuario = usuario;
            //usuario1.Senha.ToString(null);
            return View();
        }

        public ActionResult Remover(int id)
        {
            var dao = new UsuarioDAO();
            Usuario usuario = dao.BuscaPorIdWhere(id);
            dao.Remover(usuario);
            return RedirectToAction("Index");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Login", "Login");
        }
    }
}

Projeto04/Views/Home/About.cshtml
<h2>O que e o sistema?</h2>
<h4>A ideia é que se algum desenvolvedor precisar usar uma ferramenta de licenças limitadas e não tiver acesso, ele possa consultar em algum lugar alguém que não esteja utilizando e comunicar com o gestor para emprestar a licença, informando quanto tempo (em média) ele ficará com a licença.</h4>
<h4>Por fim, sabendo de quem ele retirará a licença, basta a TI fazer a troca. Isso poupará tempo da TI em ficar procurando quem não está utilizando a ferramenta e também evitará que a licença de alguém seja retirada indevidamente.</h4>

Projeto04/Views/Home/Adm.cshtml
@{ 
    Layout = "~/Views/Shared/_AdmLayout.cshtml";
}

@using Projeto02.Models.Enum
@if (Session["usuarioLogado"] == null)
{
    if ((TipoPerfil)Session["TipoPerfil"] == TipoPerfil.Administrador)
    {
        <p>
            <h3>Bem vindo ao sistema grande administrador</h3> <h1>
                @Session["nomeUsuario"].ToString()
            </h1>
        </p>
    }
    @*else
    {
        <p>
            <h3>Bem vindo ao sistema</h3> <h1>
                @Session["nomeUsuario"].ToString()
            </h1>
        </p>
    }*@
}
    <h1 class="fixed-top text-center">Tela de Cadastro</h1>

    <div class="navbar navbar-expand-lg navbar-transparent">

        @*<ul class="nav navbar-header">
                <li class="btn btn-primary" >@Html.ActionLink("Cadastrar Cargo", "Form", "Cargo")</li>
                <li class="btn btn-primary" >@Html.ActionLink("Cadastrar Equipe", "Form", "Equipe")</li>
                <li class="btn btn-primary" >@Html.ActionLink("Cadastrar Funcionario", "Form", "Funcionario")</li>
                <li class="btn btn-primary" >@Html.ActionLink("Cadastrar Software", "Form", "Software")</li>
                <li class="btn btn-primary" >@Html.ActionLink("Cadastrar Licenca", "Form", "Licenca")</li>
                <li class="btn btn-primary" >@Html.ActionLink("Cadastrar Usuario", "Form", "Usuario")</li>
                <li class="btn btn-primary" >@Html.ActionLink("Cadastrar Pedido", "Form", "SolicitacaoLicenca")</li>
            </ul>*@
        @*<ul class="nav navbar-header navbar-right">
                <li class="btn btn-primary">@Html.ActionLink("Cargos", "Index", "Cargo")</li>
                <li class="btn btn-primary">@Html.ActionLink("Equipes", "Index", "Equipe")</li>
                <li class="btn btn-primary">@Html.ActionLink("Funcionarios", "Index", "Funcionario")</li>
                <li class="btn btn-primary">@Html.ActionLink("Softwares", "Index", "Software")</li>
                <li class="btn btn-primary">@Html.ActionLink("Licencas", "Index", "Licenca")</li>
                <li class="btn btn-primary">@Html.ActionLink("Usuarios", "Visualiza", "Usuario")</li>
                <li class="btn btn-primary">@Html.ActionLink("Pedidos", "Index", "SolicitacaoLicenca")</li>
            </ul>*@
    </div>

Projeto04/Views/Home/Contact.cshtml
<h2>Contato.</h2>
<h3>Minha Pagina de contato</h3>

<address>
    São jorge do ivai, PR 87190-000<br />
    <abbr title="Phone">Celular:</abbr>
    (44) 9 8835-1153
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:matheus.marculino@benner.com.br">matheus.marculino@benner.com.br</a><br />
    <strong>Marketing:</strong> <a href="mailto:marculino_99@hotmail.com">marculino_99@hotmail.com</a>
</address>

Projeto04/Views/Home/Gestor.cshtml
@{    Layout = "~/Views/Shared/_GestorLayout.cshtml";
}

@using Projeto02.Models.Enum
@if (Session["usuarioLogado"] == null)
{
    if ((TipoPerfil)Session["TipoPerfil"] == TipoPerfil.Gestor)
    {
        <p>
            <h3>Bem vindo ao sistema grande gestor</h3> <h1>
                @Session["nomeUsuario"].ToString()
            </h1>
        </p>
    }
}

Projeto04/Views/Home/Index.cshtml
@using Projeto02.Models.Enum
@{
    ViewBag.Title = "Home Page";
}

@if (Session["usuarioLogado"] == null)
{
    if ((TipoPerfil)Session["TipoPerfil"] == TipoPerfil.Administrador)
    {
        <p>
            <h3>Bem vindo ao sistema grande administrador</h3> <h1>
                @Session["nomeUsuario"].ToString()
            </h1>
        </p>
    }
    else
    {
        <p>
            <h3>Bem vindo ao sistema</h3> <h1>
                @Session["nomeUsuario"].ToString()
            </h1>
        </p>
    }
}